network:
  ethernets:
    ens3:
      dhcp4: false
      addresses:
        - 192.168.122.100/24
    ens4:
      addresses:
        - 10.10.10.2/24
        - fc00:0:1000::2/64
      nameservers:
        addresses: [8.8.8.8]
      gateway4: 10.10.10.1          
  version: 2