- name: Setup ubuntu-trex01 container
  hosts: localhost
  become: true
  tasks:

    - name: add eth1 v4 addr
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip addr add 10.101.1.2/24 dev eth1"
      ignore_errors: yes

    - name: add eth1 v6 addr
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip addr add fc00:0:101:1::2/64 dev eth1"
      ignore_errors: yes

    - name: add eth2 v4 addr
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip addr add 10.101.2.2/24 dev eth2"
      ignore_errors: yes

    - name: add eth2 v6 addr
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip addr add fc00:0:101:2::2/64 dev eth2"
      ignore_errors: yes


    - name: add eth9 v4 addr
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip addr add 10.101.9.2/24 dev eth9"
      ignore_errors: yes

    - name: add eth9 v6 addr
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip addr add fc00:0:101:9::2/64 dev eth9"
      ignore_errors: yes

    - name: add ipv4 route
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip route add 10.0.0.0/8 via 10.101.1.1 dev eth1"
      ignore_errors: yes

    - name: add ipv6 route
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 ip -6 route add fc00:0000::/32 via fc00:0:101:1::1"
      ignore_errors: yes

    - name: copy trex config to container
      command: "docker cp trex_cfg.yaml clab-peterson-rsvp-ubuntu01:/etc/trex_cfg.yaml"
      ignore_errors: yes

    - name: start trex
      command: "docker exec -it clab-peterson-rsvp-ubuntu01 /opt/trex/v3.04/t-rex-64 -i &"
      ignore_errors: yes

