- name: Setup ubuntu-trex01 container
  hosts: localhost
  become: true
  tasks:

    - name: add eth1 v4 addr
      command: "docker exec -it clab-peterson-ubuntu01 ip addr add 10.101.1.2/24 dev eth1"
      ignore_errors: yes

    - name: add eth1 v6 addr
      command: "docker exec -it clab-peterson-ubuntu01 ip addr add fc00:0:101:1::2/64 dev eth1"
      ignore_errors: yes

    - name: add ipv4 route
      command: "docker exec -it clab-peterson-ubuntu01 ip route add 10.0.0.0/8 via 10.101.1.1 dev eth1"
      ignore_errors: yes

    - name: add ipv6 route
      command: "docker exec -it clab-peterson-ubuntu01 ip -6 route add fc00:0000::/32 via fc00:0:101:1::1"
      ignore_errors: yes

- name: copy trex config file to container
  hosts: ubuntu-trex01
  become: true
  tasks:

    - name: Copy config_baseline.json files
      copy:
        src: "{{ inventory_hostname }}/config_baseline.json"
        dest: "/etc/sonic/config_baseline.json"
        mode: 0644