services:
# Ubuntu containers
  source:
    non_xr: true
    image: ubuntu-trex:1.1
    container_name: ubuntu-trex01
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    #command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.0.95.1 && /bin/sh"
    networks:
      xrd01-host:
        ipv4_address: 10.101.1.2/24
      xrd02-host:
        ipv4_address: 10.101.2.2/24
      xrd03-host:
        ipv4_address: 10.101.3.2/24
      xrd04-host:
        ipv4_address: 10.101.4.2/24
      xrd05-host:
        ipv4_address: 10.101.5.2/24
      xrd06-host:
        ipv4_address: 10.101.6.2/24
      xrd07-host:
        ipv4_address: 10.101.7.2/24
      xrd08-host:
        ipv4_address: 10.101.8.2/24
      xrd09-host:
        ipv4_address: 10.101.9.2/24
      xrd10-host:
        ipv4_address: 10.101.10.2/24

# XRd containers
  xrd01:
    xr_startup_cfg: config-rsvp-te/xrd01.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd02:
    xr_startup_cfg: config-rsvp-te/xrd02.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd03:
    xr_startup_cfg: config-rsvp-te/xrd03.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd04:
    xr_startup_cfg: config-rsvp-te/xrd04.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd05:
    xr_startup_cfg: config-rsvp-te/xrd05.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd06:
    xr_startup_cfg: config-rsvp-te/xrd06.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd07:
    xr_startup_cfg: config-rsvp-te/xrd07.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd08:
    xr_startup_cfg: config-rsvp-te/xrd08.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd09:
    xr_startup_cfg: config-rsvp-te/xrd09.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd10:
    xr_startup_cfg: config-rsvp-te/xrd10.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Mg0/RP0/CPU0/0
  xrd11:
    xr_startup_cfg: config-rsvp-te/xrd11.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Mg0/RP0/CPU0/0

xr_l2networks:
  - ["xrd01:Gi0/0/0/0", "xrd02:Gi0/0/0/0"]
  - ["xrd01:Gi0/0/0/1", "xrd03:Gi0/0/0/0"]
  - ["xrd01:Gi0/0/0/2", "xrd04:Gi0/0/0/0"]

  - ["xrd02:Gi0/0/0/1", "xrd05:Gi0/0/0/0"]
  - ["xrd02:Gi0/0/0/2", "xrd09:Gi0/0/0/0"]

  - ["xrd03:Gi0/0/0/1", "xrd06:Gi0/0/0/0"]
  - ["xrd03:Gi0/0/0/2", "xrd10:Gi0/0/0/0"]

  - ["xrd04:Gi0/0/0/1", "xrd07:Gi0/0/0/0"]
  - ["xrd04:Gi0/0/0/2", "xrd08:Gi0/0/0/0"]

  - ["xrd05:Gi0/0/0/1", "xrd06:Gi0/0/0/1"]
  - ["xrd05:Gi0/0/0/2", "xrd08:Gi0/0/0/1"]

  - ["xrd06:Gi0/0/0/2", "xrd07:Gi0/0/0/1"]

  - ["xrd07:Gi0/0/0/2", "xrd09:Gi0/0/0/1"]

  - ["xrd08:Gi0/0/0/2", "xrd10:Gi0/0/0/1"]

  - ["xrd09:Gi0/0/0/2", "xrd10:Gi0/0/0/2"]

  - ["xrd10:Gi0/0/0/4", "xrd11:Gi0/0/0/0"]

networks:
  mgmt:
    xr_interfaces:
      - xrd01:Mg0/RP0/CPU0/0
      - xrd02:Mg0/RP0/CPU0/0
      - xrd03:Mg0/RP0/CPU0/0
      - xrd04:Mg0/RP0/CPU0/0
      - xrd05:Mg0/RP0/CPU0/0
      - xrd06:Mg0/RP0/CPU0/0
      - xrd07:Mg0/RP0/CPU0/0
      - xrd08:Mg0/RP0/CPU0/0
      - xrd09:Mg0/RP0/CPU0/0
      - xrd10:Mg0/RP0/CPU0/0
      - xrd11:Mg0/RP0/CPU0/0
    ipam:
      config:
        - subnet: 172.20.14.0/24

  xrd01-host:
    ipam:
      config:
        - subnet: 10.101.1.0/24
    xr_interfaces:
      - xrd01:Gi0/0/0/3

  xrd02-host:
    ipam:
      config:
        - subnet: 10.101.2.0/24
    xr_interfaces:
      - xrd02:Gi0/0/0/3

  xrd03-host:
    ipam:
      config:
        - subnet: 10.101.3.0/24
    xr_interfaces:
      - xrd03:Gi0/0/0/3

  xrd04-host:
    ipam:
      config:
        - subnet: 10.101.4.0/24
    xr_interfaces:
      - xrd04:Gi0/0/0/3

  xrd05-host:
    ipam:
      config:
        - subnet: 10.101.5.0/24
    xr_interfaces:
      - xrd05:Gi0/0/0/3

  xrd06-host:
    ipam:
      config:
        - subnet: 10.101.6.0/24
    xr_interfaces:
      - xrd06:Gi0/0/0/3

  xrd07-host:
    ipam:
      config:
        - subnet: 10.101.7.0/24
    xr_interfaces:
      - xrd07:Gi0/0/0/3

  xrd08-host:
    ipam:
      config:
        - subnet: 10.101.8.0/24
    xr_interfaces:
      - xrd08:Gi0/0/0/3

  xrd09-host:
    ipam:
      config:
        - subnet: 10.101.9.0/24
    xr_interfaces:
      - xrd09:Gi0/0/0/3

  xrd10-host:
    ipam:
      config:
        - subnet: 10.101.10.0/24
    xr_interfaces:
      - xrd10:Gi0/0/0/3
