# ./xr-compose -f compose-peterson-rsvp.yml -i localhost/ios-xr/xrd-vrouter:7.8.1 -l

services:
# Ubuntu containers
  source:
    non_xr: true
    image: ubuntu-trex:1.1
    container_name: ubuntu-trex01
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    #command: /bin/sh -c "ip route add 10.0.0.0/8 via 10.0.95.1 && /bin/sh"
    networks:
      xrd01-host:
        #ipv4_address: 10.10.1.2/24
      xrd02-host:
        #ipv4_address: 10.10.2.2/24
      xrd03-host:
        #ipv4_address: 10.10.3.2/24
      xrd04-host:
        #ipv4_address: 10.10.4.2/24
      xrd05-host:
        #ipv4_address: 10.10.5.2/24
      xrd06-host:
        #ipv4_address: 10.10.6.2/24
      xrd07-host:
        #ipv4_address: 10.10.7.2/24
      xrd08-host:
        #ipv4_address: 10.10.8.2/24
      xrd09-host:
        #ipv4_address: 10.10.9.2/24
      xrd10-host:
        #ipv4_address: 10.10.10.2/24

# XRd containers

  xrd01:
    environment:
      XR_INTERFACES: "pci:00:30.0"
      XR_INTERFACES: "pci:00:31.0"
      XR_INTERFACES: "pci:00:32.0"
      XR_INTERFACES: "pci:00:33.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd01.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd02:
    environment:
      XR_INTERFACES: "pci:00:34.0"
      XR_INTERFACES: "pci:00:35.0"
      XR_INTERFACES: "pci:00:36.0"
      XR_INTERFACES: "pci:00:37.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd02.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd03:
    environment:
      XR_INTERFACES: "pci:00:38.0"
      XR_INTERFACES: "pci:00:39.0"
      XR_INTERFACES: "pci:00:40.0"
      XR_INTERFACES: "pci:00:41.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd03.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd04:
    environment:
      XR_INTERFACES: "pci:00:42.0"
      XR_INTERFACES: "pci:00:43.0"
      XR_INTERFACES: "pci:00:44.0"
      XR_INTERFACES: "pci:00:45.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd04.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd05:
    environment:
      XR_INTERFACES: "pci:00:46.0"
      XR_INTERFACES: "pci:00:47.0"
      XR_INTERFACES: "pci:00:48.0"
      XR_INTERFACES: "pci:00:49.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd05.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd06:
    environment:
      XR_INTERFACES: "pci:00:50.0"
      XR_INTERFACES: "pci:00:51.0"
      XR_INTERFACES: "pci:00:52.0"
      XR_INTERFACES: "pci:00:53.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd06.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd07:
    environment:
      XR_INTERFACES: "pci:00:54.0"
      XR_INTERFACES: "pci:00:55.0"
      XR_INTERFACES: "pci:00:56.0"
      XR_INTERFACES: "pci:00:57.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd07.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd08:
    environment:
      XR_INTERFACES: "pci:00:58.0"
      XR_INTERFACES: "pci:00:59.0"
      XR_INTERFACES: "pci:00:60.0"
      XR_INTERFACES: "pci:00:61.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd08.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd09:
    environment:
      XR_INTERFACES: "pci:00:62.0"
      XR_INTERFACES: "pci:00:63.0"
      XR_INTERFACES: "pci:00:64.0"
      XR_INTERFACES: "pci:00:65.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd09.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

  xrd10:
    environment:
      XR_INTERFACES: "pci:00:66.0"
      XR_INTERFACES: "pci:00:67.0"
      XR_INTERFACES: "pci:00:68.0"
      XR_INTERFACES: "pci:00:69.0"
      XR_INTERFACES: "pci:00:70.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd10.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Gi0/0/0/4
      - Mg0/RP0/CPU0/0

  xrd11:
    environment:
      XR_INTERFACES: "pci:00:71.0"
      XR_VROUTER_DP_HUGEPAGE_MB: "1024"
    cap_add: ["SYS_RAWIO"]
    devices: ["/dev/vfio"]
    device_cgroup_rules: ["c *:* rwm"]
    xr_startup_cfg: config-rsvp-te/xrd11.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Mg0/RP0/CPU0/0

xr_l2networks:
  - ["xrd01:Gi0/0/0/0", "xrd02:Gi0/0/0/0"]
  - ["xrd01:Gi0/0/0/1", "xrd03:Gi0/0/0/0"]
  - ["xrd01:Gi0/0/0/2", "xrd04:Gi0/0/0/0"]

  - ["xrd02:Gi0/0/0/1", "xrd05:Gi0/0/0/0"]
  - ["xrd02:Gi0/0/0/2", "xrd09:Gi0/0/0/0"]

  - ["xrd03:Gi0/0/0/1", "xrd06:Gi0/0/0/0"]
  - ["xrd03:Gi0/0/0/2", "xrd10:Gi0/0/0/0"]

  - ["xrd04:Gi0/0/0/1", "xrd07:Gi0/0/0/0"]
  - ["xrd04:Gi0/0/0/2", "xrd08:Gi0/0/0/0"]

  - ["xrd05:Gi0/0/0/1", "xrd06:Gi0/0/0/1"]
  - ["xrd05:Gi0/0/0/2", "xrd08:Gi0/0/0/1"]

  - ["xrd06:Gi0/0/0/2", "xrd07:Gi0/0/0/1"]

  - ["xrd07:Gi0/0/0/2", "xrd09:Gi0/0/0/1"]

  - ["xrd08:Gi0/0/0/2", "xrd10:Gi0/0/0/1"]

  - ["xrd09:Gi0/0/0/2", "xrd10:Gi0/0/0/2"]

  - ["xrd10:Gi0/0/0/4", "xrd11:Gi0/0/0/0"]

networks:
  mgmt:
    xr_interfaces:
      - xrd01:Mg0/RP0/CPU0/0
      - xrd02:Mg0/RP0/CPU0/0
      - xrd03:Mg0/RP0/CPU0/0
      - xrd04:Mg0/RP0/CPU0/0
      - xrd05:Mg0/RP0/CPU0/0
      - xrd06:Mg0/RP0/CPU0/0
      - xrd07:Mg0/RP0/CPU0/0
      - xrd08:Mg0/RP0/CPU0/0
      - xrd09:Mg0/RP0/CPU0/0
      - xrd10:Mg0/RP0/CPU0/0
      - xrd11:Mg0/RP0/CPU0/0
    ipam:
      config:
        - subnet: 172.20.14.0/24

  xrd01-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.1.0/24
    xr_interfaces:
      - xrd01:Gi0/0/0/3

  xrd02-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.2.0/24
    xr_interfaces:
      - xrd02:Gi0/0/0/3

  xrd03-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.3.0/24
    xr_interfaces:
      - xrd03:Gi0/0/0/3

  xrd04-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.4.0/24
    xr_interfaces:
      - xrd04:Gi0/0/0/3

  xrd05-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.5.0/24
    xr_interfaces:
      - xrd05:Gi0/0/0/3

  xrd06-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.6.0/24
    xr_interfaces:
      - xrd06:Gi0/0/0/3

  xrd07-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.7.0/24
    xr_interfaces:
      - xrd07:Gi0/0/0/3

  xrd08-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.8.0/24
    xr_interfaces:
      - xrd08:Gi0/0/0/3

  xrd09-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.9.0/24
    xr_interfaces:
      - xrd09:Gi0/0/0/3

  xrd10-host:
    # ipam:
    #   config:
    #     - subnet: 10.10.10.0/24
    xr_interfaces:
      - xrd10:Gi0/0/0/3
