apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: pe0
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: clab-srv6-vpnv4-simple-control-plane
  virtualRouters:
  - localASN: 65140
    exportPodCIDR: true
    mapSRv6VRFs: true
    neighbors:
    - peerAddress: "10.42.1.1"
      peerASN: 65042
      families:
       - afi: ipv4
         safi: mpls_vpn
    - peerAddress: "10.43.1.1"
      peerASN: 65042
      families:
       - afi: ipv4
         safi: mpls_vpn

# kubectl annotate --overwrite nodes clab-srv6-vpnv4-simple-control-plane cilium.io/bgp-virtual-router.65001="router-id=172.0.0.2,srv6-responder=true"
