apiVersion: isovalent.com/v1alpha1
kind: IsovalentVRF
metadata:
  name: blue
spec:
  vrfID: 1000012
  importRouteTarget: "12:12"
  exportRouteTarget: "12:12"
  locatorPoolRef: pool0
  rules:
  - selectors:
    - endpointSelector:
        matchLabels:
          vrf: blue
    destinationCIDRs:
    - 0.0.0.0/0

