# This is the network config written by 'subiquity'
network:
  ethernets:
    ens3:
      addresses:
        - 192.168.122.242/24
    ens4:
      addresses:
        - 10.42.1.2/24
        - fc00:0000:42:1::2/64
      nameservers:
        addresses: [10.200.96.87]
      gateway4: 10.42.1.1
      routes:
        # - to: 10.0.0.0/8
        #   via: 10.42.1.1 
        - to: fc00:0000::/32
          via: fc00:0000:42:1::1  
          on-link: true
        
  version: 2