# helm install cilium isovalent/cilium --version 1.15.6 --namespace kube-system -f cilium-enterprise-values.yaml

hubble:
  enabled: false
  relay:
    enabled: false
nodeinit:
  enabled: true
ipam:
  mode: cluster-pool


# kubectl get ds -n kube-system cilium -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d: -f1
