apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
  - name: "65142"
    localASN: 65142
    peers:
    - name: "v6-peer-65042-xrd42"
      peerASN: 65042
      peerAddress: fc00:0:42:1::1
      peerConfigRef:
        name: "cilium-v6-peer"
    - name: "v4-peer-65042-xrd42"
      peerASN: 65042
      peerAddress: 10.42.1.1
      peerConfigRef:
        name: "cilium-v4-peer"

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-v4-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

metadata:
  name: cilium-v6-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv6
      safi: unicast
    - afi: ipv4
      safi: mpls_vpn
      advertisements:
        matchLabels:
          advertise: "bgp"