apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16,fc00:0000:200:0::/56
  serviceSubnet: 10.96.0.0/16,fc00:0000:42:2::/112
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.42.1.2"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 10.42.1.2,fc00:0:42:1::2