apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
networking:
  podSubnet: "10.200.0.0/16,2001:db8:42:0::/56"
  serviceSubnet: "10.96.0.0/16,2001:db8:42:1::/112"
  dualStack: true   

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.10.10.2"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "10.10.10.2"