#  The 4-node topology is comprised of routers xrd00 thru xrd03
#  ./xrd-compose -f docker-compose-4-node.yml -i ios-xr/xrd-control-plane:7.8.1 -l

services:

# XRd
  xrd00:
    xr_startup_cfg: ../configs/4-node/xrd00.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd01:
    xr_startup_cfg: ../configs/4-node/xrd01.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd02:
    xr_startup_cfg: ../configs/4-node/xrd02.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0
  xrd03:
    xr_startup_cfg: ../configs/4-node/xrd03.cfg
    xr_interfaces:
      - Gi0/0/0/0
      - Gi0/0/0/1
      - Gi0/0/0/2
      - Gi0/0/0/3
      - Mg0/RP0/CPU0/0

# Topology
#  
#  r02---r03
#   | \  / |
#   |  \/  |
#   |  /\  |
#   | /  \ |
#  r00    r01

xr_l2networks:
  - ["xrd00:Gi0/0/0/0", "xrd02:Gi0/0/0/0"]
  - ["xrd00:Gi0/0/0/1", "xrd03:Gi0/0/0/0"]
  - ["xrd01:Gi0/0/0/0", "xrd02:Gi0/0/0/1"]
  - ["xrd01:Gi0/0/0/1", "xrd03:Gi0/0/0/1"] 
  - ["xrd02:Gi0/0/0/2", "xrd03:Gi0/0/0/2"]

networks:
  mgmt:
    xr_interfaces:
      - xrd00:Mg0/RP0/CPU0/0
      - xrd01:Mg0/RP0/CPU0/0
      - xrd02:Mg0/RP0/CPU0/0
      - xrd03:Mg0/RP0/CPU0/0

    ipam:
      config:
        - subnet: 172.40.0.0/24
  xrd00-host:
    ipam:
      config:
        - subnet: 10.101.1.0/24
    xr_interfaces:
      - xrd00:Gi0/0/0/2
  xrd01-host:
    ipam:
      config:
        - subnet: 10.102.1.0/24
    xr_interfaces:
      - xrd01:Gi0/0/0/2