apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: cluster00-wkr00
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cluster00-wkr00
  virtualRouters:
  - localASN: 65045
    exportPodCIDR: true
    mapSRv6VRFs: true
    srv6LocatorPoolSelector:
      matchLabels:
        export: "true"
    neighbors:
    - peerAddress: "10.45.1.1/32"
      peerASN: 65040
      families:
       - afi: ipv4
         safi: unicast
    - peerAddress: "2001:db8:18:45::1/128"
      peerASN: 65040
      families:
        - afi: ipv6
          safi: unicast
        - afi: ipv4
          safi: mpls_vpn