---
- name: Copy configuration files to target hosts
  hosts: sonic_nodes
  become: true
  tasks:
    - name: Copy configuration files
      copy:
        src: "{{ hostvars[inventory_hostname]['config_file'] }}"
        dest: "{{ config_path }}/{{ inventory_hostname }}"
        mode: 0644
