---
- name: Copy configuration files to target hosts
  hosts: my_target_hosts
  become: true
  tasks:
    - name: Copy configuration files
      copy:
        src: "files/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644
