---
- name: Copy configuration files to target hosts with backup and config reload
  hosts: sonic_nodes
  become: true
  tasks:
    - name: Create a backup of the existing configuration file
      command: mv /etc/sonic/config_db.json /etc/sonic/config_db.json.bak
      args:
        creates: /etc/sonic/config_db.json.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy new configuration files
      copy:
        src: "files/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644

    # - name: Reload configuration
    #   expect:
    #     command: sudo config reload
    #     #command: sudo config load /etc/sonic/config_db.json
    #     responses:
    #       '.*y/N.*': 'y'
    #   ignore_errors: yes
    #   when: backup_result is not failed
    #   wait_for: 
    #     - result[0] contains Reloading
    #     - result[1] contains Reinitializing
    #   async: 30  # Set the async timeout value to 180 seconds (adjust as needed)
    #   poll: 0
    #   register: reload_result

    - name: Reload configuration
      expect:
        command: sudo config reload
        responses:
          #'.*y/N.*': 'y'
          'Clear current config and reload config in config_db format from the default config file(s) ? [y/N]:': 'y'
      ignore_errors: yes
      when: backup_result is not failed
      async: 90  # Set the async timeout value to 180 seconds (adjust as needed)
      poll: 5
      register: reload_result

    - debug: msg="{{ reload_result.stdout }}"

    - debug: msg="{{ reload_result.stderr }}"