---
- name: Copy configuration files to target hosts with backup and config reload
  hosts: sonic_nodes
  become: true
  tasks:
    - name: Create a backup of the existing configuration file
      command: mv /etc/sonic/config_db.json /etc/sonic/config_db.json.bak
      args:
        creates: /etc/sonic/config_db.json.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy new configuration files
      copy:
        src: "files/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644

    - name: Reload configuration
      expect:
        # command: sudo config reload
        command: sudo config load /etc/sonic/config_db.json
        responses:
          '.*y/N.*': 'y'
      ignore_errors: yes
      when: backup_result is not failed
      async: 30  # Set the async timeout value to 180 seconds (adjust as needed)
      poll: 0
      register: reload_result

    - name: Restart SwSS
      expect:
        command: sudo systemctl restart swss
        responses:
          '.*y/N.*': 'y'
      ignore_errors: yes
      when: backup_result is not failed
      async: 60  # Set the async timeout value to 180 seconds (adjust as needed)
      poll: 0
      register: reload_result


    # - name: Display 'config reload' output
    #   debug:
    #     var: reload_result.stdout_lines
    #   when: reload_result.stdout_lines is defined

    - name: Save 'config reload' output to log file
      copy:
        content: "{{ reload_result.stdout }}"
        dest: /home/brmcdoug/log_file.log
      when: reload_result.stdout is defined