# This is the network config written by 'subiquity'
network:
  ethernets:
    ens4:
      dhcp4: true
    ens5:
      addresses:
        - 24.1.1.2/26
        - fcbb:bb00:0100:1::2/64
      routes:
        - to: 24.1.1.64/26
          via: 24.1.1.1 
        - to: 24.1.1.128/26
          via: 24.1.1.1 
        - to: 24.1.1.192/26
          via: 24.1.1.1 
        - to: fcbb:bb00::/32
          via: fcbb:bb00:100:1::1  
          on-link: true
        
  version: 2