apiVersion: v1
kind: Pod
metadata:
  namespace: blue
  labels:
    app: alpine-ping
    vrf: blue
  name: bluepod0
spec:
  containers:
  - image: alpine:latest
    name: bluepod0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"