apiVersion: v1
kind: Pod
metadata:
  namespace: blue
  labels:
    app: alpine-ping
    vrf: blue
  name: bluepod1
spec:
  containers:
  - image: alpine:latest
    name: bluepod1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"