apiVersion: v1
kind: Pod
metadata:
  namespace: green
  labels:
    app: alpine-ping
    vrf: red
  name: redpod0
spec:
  containers:
  - image: alpine:latest
    name: redpod0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"