apiVersion: v1
kind: Pod
metadata:
  namespace: red
  labels:
    app: alpine-ping
    vrf: red
  name: redpod1
spec:
  containers:
  - image: alpine:latest
    name: redpod1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"