apiVersion: isovalent.com/v1alpha1
kind: IsovalentVRF
metadata:
  name: red
spec:
  vrfID: 1000009
  importRouteTarget: "9:9"
  exportRouteTarget: "9:9"
  locatorPoolRef: pool0
  rules:
  - selectors:
    - endpointSelector:
        matchLabels:
          vrf: red
    destinationCIDRs:
    - 0.0.0.0/0

