---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-cp-22
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-cp-22
  bgpInstances:
  - name: "asn4200001000"
    localASN: 4200001000
    peers:
    - name: "r02"
      peerASN: 4200000002
      peerAddress: fc00:0:1000::1
      peerConfigRef:
        name: "fabric-peer"
    - name: "k8s-wkr00-22"
      peerASN: 4200001001
      peerAddress: fc00:0:1001::1
      peerConfigRef:
        name: "srv6-peer"
    - name: "k8s-wkr01-22"
      peerASN: 4200001002
      peerAddress: fc00:0:1002::1
      peerConfigRef:
        name: "srv6-peer"
    - name: "xrd99"
      peerASN: 4200001099
      peerAddress: fc00:0:1099::1
      peerConfigRef:
        name: "srv6-peer"
    vrfs:
    - vrfRef: "blue"
      rd: "1000:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-wkr00-22
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-wkr00-22
  bgpInstances:
  - name: "asn4200001001"
    localASN: 4200001001
    peers:
    - name: "r03"
      peerASN: 4200000003
      peerAddress: fc00:0:1001::1
      peerConfigRef:
        name: "fabric-peer"
    vrfs:
    - vrfRef: "blue"
      rd: "1001:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config
    - vrfRef: "green"
      rd: "1001:1"
      importRTs:
        - "5:5"
      exportRTs:
        - "5:5"
      configRef: green-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-wkr01-22
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-wkr01-22
  bgpInstances:
  - name: "asn4200001002"
    localASN: 4200001002
    peers:
    - name: "r04"
      peerASN: 4200000004
      peerAddress: fc00:0:1002::1
      peerConfigRef:
        name: "fabric-peer"
    vrfs:
    - vrfRef: "blue"
      rd: "1002:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config
    - vrfRef: "green"
      rd: "1002:1"
      importRTs:
        - "5:5"
      exportRTs:
        - "5:5"
      configRef: green-config