---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-cp-22
  bgpInstances:
  - name: "asn65000"
    localASN: 65000
    peers:
    - name: "nx02"
      peerASN: 65000
      peerAddress: fc00:0:5555::1
      peerConfigRef:
        name: "cilium-peer"
    vrfs:
    - vrfRef: "blue"
      rd: "9:9"
      importRTs:
        - "9:9"
      exportRTs:
        - "9:9"
      configRef: blue-config
