---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: k8s-cp
spec:
  bgpInstances:
    - name: "asn4200001000"
      srv6Responder: true
      peers:
        - name: "k8s-wkr-00"
          localAddress: fc00:0:1000::1
        - name: "k8s-wkr-01"
          localAddress: fc00:0:1000::1
        - name: "xrd99"
          localAddress: fc00:0:1000::1
