---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPVRFConfig
metadata:
  name: blue-config
spec:
  families:
    - afi: ipv4
      safi: mpls_vpn
      advertisements:
        matchLabels:
          advertise: "blue"

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: blue-adverts
  labels:
    advertise: blue
spec:
  advertisements:
    - advertisementType: "PodCIDR"

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentVRF
metadata:
  name: blue
spec:
  vrfID: 4
  locatorPoolRef: pool0
  rules:
  - selectors:
    - endpointSelector:
        matchLabels:
          vrf: blue
    destinationCIDRs:
    - 0.0.0.0/0

---
apiVersion: v1
kind: Namespace
metadata:
  name: blue
  labels:
    name: blue

---
apiVersion: v1
kind: Pod
metadata:
  namespace: blue
  labels:
    app: alpine-ping
    vrf: blue
  name: blue0
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: blue0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"

---
apiVersion: v1
kind: Pod
metadata:
  namespace: blue
  labels:
    app: alpine-ping
    vrf: blue
  name: blue1
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: blue1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"

---
apiVersion: v1
kind: Namespace
metadata:
  name: dolphin
  labels:
    name: dolphin

---
apiVersion: v1
kind: Pod
metadata:
  namespace: dolphin
  labels:
    app: alpine-ping
    vrf: blue
  name: dolphin0
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: blue0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"